### PR TITLE
Add __PACKED_STRUCT for inter processors structures

### PR DESCRIPTION
**Pull request by danny4478**
This change is [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/32)

### CODE REVIEW

**Comment by alzix** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[spm/spm_internal.h, line 81 at r1](https://reviewable.io/reviews/kfnta/mbed-os/32#-LEdnpeJDvEr4zkfGCSM:-LEdnpeJDvEr4zkfGCSN:b-lpnigr) ([raw file](https://github.com/kfnta/mbed-os/blob/2072602c7de10d32f818fbe4eb81fd1d07666e03/spm/spm_internal.h#L81)):*
> ```objc
>  * Structure containing data sent from NSPE for ROT_SRV call.
>  */
> typedef __PACKED_STRUCT spm_pending_call_msg {
> ```

please add comment to the struct description about what we are using `__PACKED_STRUCT` in both cases.
to be on the safe side - can you also check if we have macro for `__attribute__((aligned(32)))` if yes we can consider adding it to the struct.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/32)*

**Comment by mikisch81** [comment]
@danny4478  please rebase this branch on top of `dev-spm` again.

**Comment by alzix** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @danny4478, @mikisch81, and @romkuz01)

---

*[spm/spm_internal.h, line 79 at r2](https://reviewable.io/reviews/kfnta/mbed-os/32#-LEpnPpj8p0R-oDRZuLD:-LEpnPpj8p0R-oDRZuLE:b6f37yw) ([raw file](https://github.com/kfnta/mbed-os/blob/60b5901b6e41d46f722bd210007bea86f4fa6cc3/spm/spm_internal.h#L79)):*
> ```objc
> 
> 
> // spm_pending_call_msg struct below is packed since in a dual processor solution
> ```

please consider something alike:

```C
// spm_pending_call_msg struct below is packed since in a dual MCU solution
// it is allocated and filled in by non-secure MCU but read from secure MCU
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/32)*

**Comment by mikisch81** [comment]
@alzix what is this strange merge-commit?

**Pull request merged**
