### PR TITLE
Build PSA for ARM and IAR

### PR DESCRIPTION
**Pull request by mikisch81**
- Modify sct/icf files
- Fix compilation errors

Tested on our CI, build is successfull: [https://jenkins-internal.mbed.com/blue/organizations/jenkins/kfnta-mbed-os-tests-spm/detail/kfnta-mbed-os-tests-spm/491/pipeline/](https://jenkins-internal.mbed.com/blue/organizations/jenkins/kfnta-mbed-os-tests-spm/detail/kfnta-mbed-os-tests-spm/491/pipeline/)

Tests are not running with the ARM/IAR images, need to investigate.

---
This change is [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/72)

### CODE REVIEW

**Comment by orenc17** [comment]
@mikisch81 i've run the smoke binaries and only ARMCC is stuck

**Comment by alzix** [comment]
:lgtm:
do we have a clue why tests get stuck on ARMCC image

**Comment by mikisch81** [comment]
> 
> 
> :lgtm:
> do we have a clue why tests get stuck on ARMCC image

Not yet, need to debug it

**Comment by mikisch81** [comment]
All toolchains compiles and smoke runs on them

**Pull request merged**
