### PR TITLE
Add detection of circular call dependencies between the partitions

### PR DESCRIPTION
**Pull request by romkuz01**
Add a new function test_check_circular_call_dependencies() and call it during manifest correctness checks in validate_partition_manifests().

Also add unit tests for this new function.

---
This change is [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/28)

### CODE REVIEW

**Comment by mikisch81** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[tools/spm/generate_partition_code.py, line 405 at r2](https://reviewable.io/reviews/kfnta/mbed-os/28#-LDuDgq917rcVhv-wpg9:-LDuDgq917rcVhv-wpgA:b3ijkeq) ([raw file](https://github.com/kfnta/mbed-os/blob/fbe825469acb8750c0b24f19487e91cbb9a4248e/tools/spm/generate_partition_code.py#L405)):*
> ```Python
> 
> 
> def check_circular_call_dependencies(manifests):
> ```

From the name of this function one can conclude that `true` means that there is a circular dependency while the implementation does the opposite, maybe rename this function?

Also please add function description

---

*[tools/test/spm/test_generate_partition_code.py, line 776 at r2](https://reviewable.io/reviews/kfnta/mbed-os/28#-LDuIurKDBjzs0IwP2mS:-LDuIqQp9GbauUVzx4zD:bjoni1k) ([raw file](https://github.com/kfnta/mbed-os/blob/fbe825469acb8750c0b24f19487e91cbb9a4248e/tools/test/spm/test_generate_partition_code.py#L776)):*
> ```Python
> 
> 
> circular_call_dependency_params = {
> ```

When [https://jira.arm.com/browse/IOTSEC-674](IOTSEC-674) will be implemented than build tool will fail build if there are partitions with `non_secure_clients` set to `false` and aren't referenced by any other partition in the system, so be aware there are no "orphan" partitions in this list (or set `non_secure_clients` to `true`). 

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/28)*

**Comment by alzix** [comment]
*[tools/test/spm/test_generate_partition_code.py, line 776 at r2](https://reviewable.io/reviews/kfnta/mbed-os/28#-LDuIurKDBjzs0IwP2mS:-LE8cjGY2lp-dibKYUsI:b-s4wy9k) ([raw file](https://github.com/kfnta/mbed-os/blob/fbe825469acb8750c0b24f19487e91cbb9a4248e/tools/test/spm/test_generate_partition_code.py#L776)):*
<details><summary><i>Previously, mikisch81 (Michael Schwarcz) wrote…</i></summary><blockquote>

When [https://jira.arm.com/browse/IOTSEC-674](IOTSEC-674) will be implemented than build tool will fail build if there are partitions with `non_secure_clients` set to `false` and aren't referenced by any other partition in the system, so be aware there are no "orphan" partitions in this list (or set `non_secure_clients` to `true`). 
</blockquote></details>

we will handle it as a part of IOTSEC-674 more tests will also be affected

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/28)*

**Comment by mikisch81** [comment]
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[tools/test/spm/test_generate_partition_code.py, line 776 at r2](https://reviewable.io/reviews/kfnta/mbed-os/28#-LDuIurKDBjzs0IwP2mS:-LE8n6zmCzml-E7vwo5X:b32w0x) ([raw file](https://github.com/kfnta/mbed-os/blob/fbe825469acb8750c0b24f19487e91cbb9a4248e/tools/test/spm/test_generate_partition_code.py#L776)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

we will handle it as a part of IOTSEC-674 more tests will also be affected
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/28)*

**Pull request merged**
