### PR TITLE
Changing PREPROCESSOR defines *_FLASH_* to *_ROM_*

### PR DESCRIPTION
**Pull request by mikisch81**
Aligning with #79, mainly to [Alexs' comment](https://github.com/kfnta/mbed-os/pull/79/files#r232814245)

---
This change is [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/80)

### CODE REVIEW

**Comment by alzix** [comment]
how do you suggest to merge it? After Jimmy's PR or instead?

**Comment by mikisch81** [comment]
> 
> 
> how do you suggest to merge it? After Jimmy's PR or instead?

before Jimmys' PR

**Comment by alzix** [comment]
then go ahead and do it. but it seems it includes Jimmy's changes

**Comment by mikisch81** [comment]
Actually it does not contains Jimmy changes, but complement them.

**Pull request merged**
