### PR TITLE
Another glorious build system fix

### PR DESCRIPTION
**Pull request by orenc17**
Tested with secure_time over IPC
Export not tested yet

mbed-os PR ARMmbed/mbed-os#6867

### CODE REVIEW

**Comment by mikisch81** [comment]
I guess you will give a different PR name to ARMmbed... 😊

**Comment by mikisch81** [comment]
Also for the ARMmbed PR a description of the changes may save some ping pong with the maintainers

**Comment by theotherjimmy** [comment]
@mikisch81 It will for maintainers other than me. I requested this.

**Comment by alzix** [comment]
@orenc17 is this PR ready to be merged? Were all the flows tested? Compile/Test/Export?

**Comment by orenc17** [comment]
@alzix this one is ready

**Comment by mikisch81** [comment]
Pushed upstream

**Pull request closed without merging**
