### PR TITLE
Initial IRQ support

### PR DESCRIPTION
**Pull request by orenc17**
This change is [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)

### CODE REVIEW

**Comment by orenc17** [comment]
/morph build
RaaS connection error

**Comment by alzix** [comment]
Reviewed 2 of 5 files at r1, 2 of 3 files at r3.
Review status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @orenc17, @alzix, @mikisch81, @danny4478, and @romkuz01)

---

*[spm/spm_internal.h, line 44 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiCRJ28sTBxiQJYcbq:-LEiCRJ28sTBxiQJYcbr:b-gc3ftt) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_internal.h#L44)):*
> ```objc
> 
> /*
>  * IRQ signal translator definition.
> ```

document your assumption that this function does not return on invalid signal

---

*[spm/spm_internal.h, line 46 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiBtw81nqz1cqi9a-c:-LEiBtw81nqz1cqi9a-d:b-ath1hv) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_internal.h#L46)):*
> ```objc
>  * IRQ signal translator definition.
>  */
> typedef uint32_t (*spm_irq_signal_translator_t)(uint32_t);
> ```

lets call it `spm_signal_to_irq_mapper_t`

---

*[spm/spm_internal.h, line 152 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiBqsj877XvyST9B72:-LEiBqsj877XvyST9B73:b25rxmx) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_internal.h#L152)):*
> ```objc
>     const uint32_t extern_sids_count; /* Number of Root of Trust Services which the partition can connect to.*/
>     osMutexId_t mutex; /* Mutex for all rot_service's queues operations. */
>     spm_irq_signal_translator_t irq_translator; /* Pointer to a function that translates signal to irq number*/
> ```

let's call it irq_mapper

---

*[spm/spm_server.c, line 545 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiC9_M7ytWWwb_6zDs:-LEiC9_M7ytWWwb_6zDt:b-nyicgf) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_server.c#L545)):*
> ```C
>         SPM_PANIC("Try to clear an interrupt flag without declaring IRQ");
>     }
> ```

add assertion for irq_signal is within `curr_partition->flags_interrupts`

---

*[spm/spm_server.c, line 546 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiCh1r2xMrKas_42Je:-LEiCh1r2xMrKas_42Jf:bvsttjp) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_server.c#L546)):*
> ```C
>     }
> 
>     NVIC_EnableIRQ(curr_partition->irq_translator(irq_signal));
> ```

create a temp variable and add assert the

---

*[tools/spm/templates/psa_common.c.tpl, line 97 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiE29b-oWPCVnNBxym:-LEiE29b-oWPCVnNBxyn:bogaxda) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/tools/spm/templates/psa_common.c.tpl#L97)):*
> ```Smarty
>     {% for irq in partition.irqs %}
> 
> void spm_irq_{{irq.signal}}_{{partition.name|lower}}(void)
> ```

please add description comment for this function

---

*[tools/spm/templates/psa_NAME_partition.c.tpl, line 94 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiE7hYBJUelrMGyZZ5:-LEiE7hYBJUelrMGyZZ6:bogaxda) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/tools/spm/templates/psa_NAME_partition.c.tpl#L94)):*
> ```Smarty
> 
> {% if partition.irqs|count > 0 %}
> uint32_t spm_{{partition.name|lower}}_irq_signal_translator(uint32_t signal)
> ```

please add description comment for this function

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by orenc17** [comment]
Review status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @alzix, @mikisch81, @danny4478, and @romkuz01)

---

*[spm/spm_internal.h, line 44 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiCRJ28sTBxiQJYcbq:-LEihtMy2MTEpTKN9xyF:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_internal.h#L44)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

document your assumption that this function does not return on invalid signal
</blockquote></details>

Done.

---

*[spm/spm_internal.h, line 46 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiBtw81nqz1cqi9a-c:-LEii0oE2MzxGcvkkBNT:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_internal.h#L46)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

lets call it `spm_signal_to_irq_mapper_t`
</blockquote></details>

Done.

---

*[spm/spm_internal.h, line 152 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiBqsj877XvyST9B72:-LEiiAdUCW9dVLsChpvM:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_internal.h#L152)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

let's call it irq_mapper
</blockquote></details>

Done.

---

*[spm/spm_server.c, line 545 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiC9_M7ytWWwb_6zDs:-LEiit99E9k4onpHVwxh:barszem) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_server.c#L545)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

add assertion for irq_signal is within `curr_partition->flags_interrupts`
</blockquote></details>

Done.
implemented in the autogenerated function as it will be faster

---

*[spm/spm_server.c, line 546 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiCh1r2xMrKas_42Je:-LEilNEfC0A3kphn2WKR:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_server.c#L546)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

create a temp variable and add assert the
</blockquote></details>

Done.

---

*[tools/spm/templates/psa_common.c.tpl, line 97 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiE29b-oWPCVnNBxym:-LEijf94Dp_PbUdt44eo:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/tools/spm/templates/psa_common.c.tpl#L97)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

please add description comment for this function
</blockquote></details>

Done.

---

*[tools/spm/templates/psa_NAME_partition.c.tpl, line 94 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiE7hYBJUelrMGyZZ5:-LEik9FaDSOnGtYIp92-:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/tools/spm/templates/psa_NAME_partition.c.tpl#L94)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

please add description comment for this function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by mikisch81** [comment]
@orenc17 please rebase this branch on top of `dev-spm` again.

**Comment by alzix** [comment]
Reviewed 4 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed, 6 unresolved discussions (waiting on @alzix, @orenc17, @mikisch81, @danny4478, and @romkuz01)

---

*[spm/spm_internal.h, line 45 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEppMH3BFMZjMbVgR38:-LEppMH3BFMZjMbVgR39:borxr03) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/spm/spm_internal.h#L45)):*
> ```objc
> /*
>  * IRQ signal translator definition.
>  * The function should not return on invalid signal.
> ```

The function ~should~ not return on invalid signal.
The function **will not** not return on invalid signal.

---

*[spm/spm_server.c, line 545 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiC9_M7ytWWwb_6zDs:-LEpqjbr5jpixz8GnXi6:b7k0kgi) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_server.c#L545)):*
<details><summary><i>Previously, orenc17 (Oren Cohen) wrote…</i></summary><blockquote>

Done.
implemented in the autogenerated function as it will be faster
</blockquote></details>

it is not faster and more error prone. this is a user input check, thus SPM_PANIC should be used - you have added SPM_ASSERT.
I prefer to check all input arguments in the receiving function and not passing them to internal ones, since it makes it harder to distinguish between user input and internal data.

Just add - i bet you can't do faster implementation :smile: 

```C
if (0 == (curr_partition->flags_interrupts & irq_signal)) {
    SPM_PANIC(".....");
}
```

---

*[spm/spm_server.c, line 547 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEppAUt2GG97goYDPtS:-LEppAUt2GG97goYDPtT:b-utit7v) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/spm/spm_server.c#L547)):*
> ```C
> 
>     bool is_one_bit = ((irq_signal != 0) && !(irq_signal & (irq_signal - 1)));
>     SPM_ASSERT(is_one_bit);
> ```

should use SPM_PANIC when validating user input

---

*[tools/spm/templates/psa_NAME_partition.c.tpl, line 137 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEpq9Fm2RQK6jVZoy6t:-LEpq9Fm2RQK6jVZoy6u:b-oe3xbn) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/tools/spm/templates/psa_NAME_partition.c.tpl#L137)):*
> ```Smarty
> 
>     {% for irq in partition.irqs %}
>     NVIC_EnableIRQ({{irq.line_num}});
> ```

i'm not sure about this one - need to think it through. 
IMHO this and other NVIC initial configuration should not be part of SPM.

@adrianlshaw - can i have your opinion on this?

---

*[tools/spm/templates/psa_NAME_partition.h.tpl, line 43 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEpt2LZ2RnoQU33X2ss:-LEpt2LZ2RnoQU33X2st:b-p8zhwj) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/tools/spm/templates/psa_NAME_partition.h.tpl#L43)):*
> ```Smarty
> {% endfor %}
> 
> #define {{partition.name|upper}}_WAIT_ANY_IRQ_MSK (\
> ```

consider not defining this macro at all if no IRQs are requested - this can provide good hint to partition developer - as his code wont compile if his is doing anything wrong

---

*[tools/spm/templates/psa_NAME_partition.h.tpl, line 56 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEpsYLi9XUycLUqB2o9:-LEpsYLi9XUycLUqB2oA:bg9sivj) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/tools/spm/templates/psa_NAME_partition.h.tpl#L56)):*
> ```Smarty
> {% endfor %}
> 
> #define {{partition.name|upper}}_WAIT_ANY_SID_MSK (\
> ```

this mask is no longer needed - partition developers cannot longer use it.
they have wait_any() and wait_interrupt() APIs. The second can only receive ANY_IRQ_MSK.
This is a leftover form FFv0.5 implementation - please remove it 

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by orenc17** [comment]
Review status: all files reviewed, 6 unresolved discussions (waiting on @alzix, @orenc17, @mikisch81, @danny4478, and @romkuz01)

---

*[spm/spm_internal.h, line 45 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEppMH3BFMZjMbVgR38:-LEs5SwGCd-zbGdcxAbl:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/spm/spm_internal.h#L45)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

The function ~should~ not return on invalid signal.
The function **will not** not return on invalid signal.
</blockquote></details>

Done.

---

*[spm/spm_server.c, line 545 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiC9_M7ytWWwb_6zDs:-LEs6bPg-oKBhbPKWIU0:bfr5ju0) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_server.c#L545)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

it is not faster and more error prone. this is a user input check, thus SPM_PANIC should be used - you have added SPM_ASSERT.
I prefer to check all input arguments in the receiving function and not passing them to internal ones, since it makes it harder to distinguish between user input and internal data.

Just add - i bet you can't do faster implementation :smile: 

```C
if (0 == (curr_partition->flags_interrupts & irq_signal)) {
    SPM_PANIC(".....");
}
```
</blockquote></details>

Implemented in partition template

---

*[spm/spm_server.c, line 547 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEppAUt2GG97goYDPtS:-LEs7SmODp1JpkAY-sr2:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/spm/spm_server.c#L547)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

should use SPM_PANIC when validating user input
</blockquote></details>

Done.

---

*[tools/spm/templates/psa_NAME_partition.h.tpl, line 43 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEpt2LZ2RnoQU33X2ss:-LEs8cH-6-Xo1BKcTCnQ:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/tools/spm/templates/psa_NAME_partition.h.tpl#L43)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

consider not defining this macro at all if no IRQs are requested - this can provide good hint to partition developer - as his code wont compile if his is doing anything wrong
</blockquote></details>

Done.

---

*[tools/spm/templates/psa_NAME_partition.h.tpl, line 56 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEpsYLi9XUycLUqB2o9:-LEsFnr00j3rRIb5WPUr:b-z2fl3y) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/tools/spm/templates/psa_NAME_partition.h.tpl#L56)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

this mask is no longer needed - partition developers cannot longer use it.
they have wait_any() and wait_interrupt() APIs. The second can only receive ANY_IRQ_MSK.
This is a leftover form FFv0.5 implementation - please remove it 
</blockquote></details>

this is still being used, this value is stored in partition->flags_rot_srv

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by alzix** [comment]
Reviewed 1 of 5 files at r7.
Review status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @alzix, @orenc17, @mikisch81, @danny4478, and @romkuz01)

---

*[tools/spm/templates/psa_NAME_partition.c.tpl, line 137 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEpq9Fm2RQK6jVZoy6t:-LFDBU2X4PMw4_VjJgZk:b-xqn8un) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/tools/spm/templates/psa_NAME_partition.c.tpl#L137)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

i'm not sure about this one - need to think it through. 
IMHO this and other NVIC initial configuration should not be part of SPM.

@adrianlshaw - can i have your opinion on this?
</blockquote></details>

move this code to the example branch

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by alzix** [comment]
Reviewed 2 of 5 files at r7.
Review status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @alzix, @orenc17, @mikisch81, @danny4478, and @romkuz01)

---

*[spm/spm_server.c, line 545 at r3](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEiC9_M7ytWWwb_6zDs:-LFDFN9v2ifBbXg8Lxa4:bvdzyag) ([raw file](https://github.com/kfnta/mbed-os/blob/aeced25069d8d5f1bb525bf3debfbd8f935ac75a/spm/spm_server.c#L545)):*
<details><summary><i>Previously, orenc17 (Oren Cohen) wrote…</i></summary><blockquote>

Implemented in partition template
</blockquote></details>

please add panic here!

---

*[spm/spm_server.c, line 545 at r4](https://reviewable.io/reviews/kfnta/mbed-os/33#-LFDFRvvBDeQYf-DqwmJ:-LFDFRvvBDeQYf-DqwmK:bomr7s2) ([raw file](https://github.com/kfnta/mbed-os/blob/2ffbb99dd01deedbda3058a05f679182ccb680b3/spm/spm_server.c#L545)):*
> ```C
>         SPM_PANIC("Try to clear an interrupt flag without declaring IRQ");
>     }
> ```

note that this function should validate that signal is only in IRQ range excluding reserved signals

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by alzix** [comment]
Reviewed 1 of 5 files at r7.
Review status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @alzix, @orenc17, @mikisch81, @danny4478, and @romkuz01)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by alzix** [comment]
Reviewed 1 of 5 files at r7.
Review status: all files reviewed, 3 unresolved discussions (waiting on @orenc17, @mikisch81, @danny4478, and @romkuz01)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by orenc17** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @alzix, @mikisch81, @danny4478, and @romkuz01)

---

*[spm/spm_server.c, line 545 at r4](https://reviewable.io/reviews/kfnta/mbed-os/33#-LFDFRvvBDeQYf-DqwmJ:-LFDQew5AAQaYGy349HX:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/2ffbb99dd01deedbda3058a05f679182ccb680b3/spm/spm_server.c#L545)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

note that this function should validate that signal is only in IRQ range excluding reserved signals
</blockquote></details>

Done.

---

*[tools/spm/templates/psa_NAME_partition.c.tpl, line 137 at r5](https://reviewable.io/reviews/kfnta/mbed-os/33#-LEpq9Fm2RQK6jVZoy6t:-LFDOI4a1fjGrUOUeUzV:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/d0b39a672e5d355652b9b923eb6c5d88921bc5c5/tools/spm/templates/psa_NAME_partition.c.tpl#L137)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

move this code to the example branch
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by alzix** [comment]
Reviewed 2 of 2 files at r8.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mikisch81, @danny4478, and @romkuz01)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by alzix** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mikisch81, @danny4478, and @romkuz01)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33#-:-LFDRADV3Dig_3d_A2vD:bnfp4nl)*

**Comment by orenc17** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @mikisch81, @danny4478, and @romkuz01)

---

*[spm/spm_internal.h, line 45 at r8](https://reviewable.io/reviews/kfnta/mbed-os/33#-LFGj3KJ5IE08mtkoenX:-LFGrl1nBO-zK2N83NTS:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/cc8d4eedc22e429e1adead3c01bf56246c91974a/spm/spm_internal.h#L45)):*
<details><summary><i>Previously, mikisch81 (Michael Schwarcz) wrote…</i></summary><blockquote>

translator -> mapper like in the function ponter name
</blockquote></details>

Done.

---

*[spm/spm_internal.h, line 159 at r8](https://reviewable.io/reviews/kfnta/mbed-os/33#-LFGjFhv1oOV_PfJh3Yz:-LFGrxw842HPOJ6CSGR2:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/cc8d4eedc22e429e1adead3c01bf56246c91974a/spm/spm_internal.h#L159)):*
<details><summary><i>Previously, mikisch81 (Michael Schwarcz) wrote…</i></summary><blockquote>

..a function which maps signal to irq number
</blockquote></details>

Done.

---

*[spm/spm_server.c, line 552 at r8](https://reviewable.io/reviews/kfnta/mbed-os/33#-LFGkDuD87yDRY_jHCrq:-LFGs34M7dYCOOfKTJAF:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/cc8d4eedc22e429e1adead3c01bf56246c91974a/spm/spm_server.c#L552)):*
<details><summary><i>Previously, mikisch81 (Michael Schwarcz) wrote…</i></summary><blockquote>

signum -> signal
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33)*

**Comment by mikisch81** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r7, 2 of 2 files at r8.
Review status: 3 of 5 files reviewed, all discussions resolved (waiting on @alzix, @mikisch81, @danny4478, and @romkuz01)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/33#-:-LFGszR_-gOOx3xLntoV:bnfp4nl)*

**Comment by adrianlshaw** [comment]
@alzix Regarding your question, it looks fine to me. I don't see an issue with enable/disabling partition IRQ lines dynamically from SPM, as to me this doesn't count as "initial" :-)

**Pull request merged**
