### PR TITLE
Secure time api split

### PR DESCRIPTION
**Pull request by mikisch81**
Split the secure-time API to external APIs (`secure_time.h` & `secure_time_spe.h`) and internal APIs (`secure_time_impl.h` & `secure_time_spe_impl.h`).

Now `secure_time.c` is only a pipe which forwards to `secure_time*_impl.c` internal implementation files.

This will make SPM integration much easier:
1. The current "PIPING" way is how the "direct" secure-time use will be.
2. For PSA way of using secure-time, `secure_time.c` will call IPC to send the data to the secure-time partition which in its' partition code will call the necessary implementation in SPE.

### CODE REVIEW

**Comment by mikisch81** [comment]
Tests are failing in ARM toolchain, need to ivestigate.

**Comment by alzix** [comment]
i see the split done differently:
1. original `secure_time.c` file renamed to `secure_time_impl.c`. All functions renamed by adding `_impl` suffix.
2. `secure_time_impl.h` may be introduced for the ease of implementation.
3. secure time NSPE client:
   - `secure_time_client.h` file - contains NSPE exposed to APIs for application use.
   - `secure_time_client_proxy.c` - contains IPC version
   - `secure_time_client_direct.c` - contains direct call version
4. secure time SPE client:
   - `secure_time_client_spe.h` - includes `secure_time_client.h` and adds SPE only exposed APIs
   - `secure_time_client_spe_proxy.c` - IPC implementation
   - `secure_time_client_spe_direct.c` - direct call version

**Comment by mikisch81** [comment]
Replaced by #9

**Pull request closed without merging**
