### PR TITLE
Make partition generation offline

### PR DESCRIPTION
**Pull request by mikisch81**
- Partition generation is now done offline and then pushed to source control.
- No more patching the mbed build system.
- Each partition generated code resides near its' json file.
- The common source file (now called psa_setup.c) resides in *mbed-os/spm*
  - Its' global data and functions are weak.
- Another psa_setup.c resides in each TEST folder with the strong global data and functions.

---
This change is [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/66)

### CODE REVIEW

**Comment by mikisch81** [comment]
@alzix pinging...

**Comment by alzix** [comment]
___
*[tools/spm/generate_partition_code.py, line 26 at r5](https://reviewable.io/reviews/kfnta/mbed-os/66#-LPa4t3m5x_a511Xm8Nk:-LPa4t3m5x_a511Xm8Nl:bejifo4) ([raw file](https://github.com/kfnta/mbed-os/blob/63365cdd7a07cd692660fef4cdb7891e4c8dd229/tools/spm/generate_partition_code.py#L26)):*
> ```Python
> SPM_CORE_ROOT = path_join(MBED_OS_ROOT, 'spm')
> SPM_TESTS_ROOT = path_join(MBED_OS_ROOT, 'TESTS', 'spm')
> SPM_TESTS = [d for d in [path_join(SPM_TESTS_ROOT, dd) for dd in os.listdir(SPM_TESTS_ROOT)] if os.path.isdir(d)]
> ```

are you a robot?
no human i know can actually understand this :)

**Comment by mikisch81** [comment]
Rebased for logical commits

/morph build

**Comment by mikisch81** [comment]
@alzix your approval was dismissed by my rebase.. 😄

**Pull request merged**
