### PR TITLE
Change osThreadFlags* commands assertions

### PR DESCRIPTION
**Pull request by orenc17**
This change is [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/47)

### CODE REVIEW

**Comment by alzix** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @orenc17, @mikisch81, and @romkuz01)

---

*[spm/spm_server.c, line 191 at r1](https://reviewable.io/reviews/kfnta/mbed-os/47#-LG0_ntO-Q-hZArF37F1:-LG0_ntP1TcprFkjGEk3:b-dko5mg) ([raw file](https://github.com/kfnta/mbed-os/blob/79fcd74d55f027f3b6ba909b5bdba2b0eb26963a/spm/spm_server.c#L191)):*
> ```C
>         SPM_ASSERT((flags & 0x80000000) != 0x80000000);
>         SPM_ASSERT((flags & rot_service->mask) == rot_service->mask);
> 		PSA_UNUSED(flags);
> ```

tabs 


---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/47)*

**Comment by orenc17** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @alzix, @mikisch81, and @romkuz01)

---

*[spm/spm_client.c, line 99 at r1](https://reviewable.io/reviews/kfnta/mbed-os/47#-LG0_WFM4BHPPB946M_C:-LG16CDZ1YyfIt7b_avp:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/79fcd74d55f027f3b6ba909b5bdba2b0eb26963a/spm/spm_client.c#L99)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

i think `(flags & 0x80000000) == 0` is clearer
</blockquote></details>

Done.

---

*[spm/spm_client.c, line 100 at r1](https://reviewable.io/reviews/kfnta/mbed-os/47#-LG0_9InD61j7kWs64lZ:-LG16V2I1Ysl_m7sct0B:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/79fcd74d55f027f3b6ba909b5bdba2b0eb26963a/spm/spm_client.c#L100)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

the result of & with bitmask can only have two values o and the value itself
so this assert can be simplified and written as: (true also for rest of the asserts)
```C
SPM_ASSERT(flags & rot_service->mask);
``
</blockquote></details>

Done.

---

*[spm/spm_server.c, line 191 at r1](https://reviewable.io/reviews/kfnta/mbed-os/47#-LG0_ntO-Q-hZArF37F1:-LG16em8CN0NOeYbxhuw:b-896fix) ([raw file](https://github.com/kfnta/mbed-os/blob/79fcd74d55f027f3b6ba909b5bdba2b0eb26963a/spm/spm_server.c#L191)):*
<details><summary><i>Previously, alzix (Alexander Zilberkant) wrote…</i></summary><blockquote>

tabs 
![✂-1](https://files.reviewableusercontent.io/images/reviewable/1101204/vAxwudv2CcxwtHB3bM8ztYXR.png)

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/47)*
<!-- Sent from Reviewable.io -->

**Comment by alzix** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mikisch81 and @romkuz01)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/47#-:-LG501J79qGCfveyl4Y-:bnfp4nl)*

**Pull request merged**
