### PR TITLE
Implement psa_framework_version & psa_version

### PR DESCRIPTION
**Pull request by orenc17**
This change is [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/41)

### CODE REVIEW

**Comment by alzix** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @orenc17, @mikisch81, @danny4478, and @romkuz01)

---

*[TESTS/spm/client_tests/client_ipc_tests.cpp, line 378 at r4](https://reviewable.io/reviews/kfnta/mbed-os/41#-LFiGUdz4otg8H-lprPj:-LFiGUdz4otg8H-lprPk:b-7yel2l) ([raw file](https://github.com/kfnta/mbed-os/blob/1f8633b55c5f4fec099c04cfa48ca89809d91204/TESTS/spm/client_tests/client_ipc_tests.cpp#L378)):*
> ```cpp
> }
> 
> void versions()
> ```

please split this test in to three separate tests

---


*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/41)*

**Comment by orenc17** [comment]
/morph build
imported splited tests from ARMmbed/mbed-os#6294

**Comment by alzix** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mikisch81, @danny4478, and @romkuz01)

---



*Comments from [Reviewable](https://reviewable.io/reviews/kfnta/mbed-os/41#-:-LFnAILUE3GB-TTc3Lx3:bnfp4nl)*

**Pull request merged**
